# Generated by Django 5.0.6 on 2024-06-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('coin', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
