# Generated by Django 5.0.6 on 2024-06-23 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_player_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_coin_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
