# Generated by Django 5.0.6 on 2024-06-30 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_business_playerbusiness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='device_id',
        ),
        migrations.AddField(
            model_name='player',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('مغازه', 'مغازه'), ('شرکت', 'شرکت'), ('تولیدی', 'تولیدی'), ('واردات', 'واردات'), ('معدن', 'معدن'), ('کارخانه', 'کارخانه')], max_length=20),
        ),
    ]
