# Generated by Django 5.0.6 on 2024-07-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_player_device_id_player_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=5),
        ),
        migrations.AddField(
            model_name='player',
            name='multitap',
            field=models.IntegerField(default=1),
        ),
    ]
