# Generated by Django 5.0.6 on 2024-07-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_player_avatar_player_multitap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
    ]
