# Generated by Django 5.0.6 on 2024-07-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='api_key',
        ),
    ]
