# Generated by Django 5.0.6 on 2024-07-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_alter_business_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='account_user',
        ),
    ]
