# Generated by Django 5.0.6 on 2024-07-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_alter_business_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='business',
            name='business_image',
            field=models.ImageField(blank=True, null=True, upload_to='Business_images/'),
        ),
    ]
