# Generated by Django 5.0.6 on 2024-07-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_player_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['id']},
        ),
    ]
