# Generated by Django 5.0.6 on 2024-07-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_player_options_alter_business_business_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_image',
            field=models.ImageField(blank=True, null=True, upload_to='Account/Business_images/'),
        ),
    ]
