# Generated by Django 5.0.6 on 2024-07-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_business_business_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.IntegerField(default=3, unique=True),
            preserve_default=False,
        ),
    ]
