# Generated by Django 5.0.6 on 2024-07-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_playercryptocurrency_playerproperty_playerstock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerbusiness',
            name='business',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
