# Generated by Django 5.0.6 on 2024-07-29 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_playerbusiness_business_delete_business'),
        ('asset', '0002_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbusiness',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asset.business'),
            preserve_default=False,
        ),
    ]
