# Generated by Django 5.0.6 on 2024-07-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_playerbusiness_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercryptocurrency',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='playerstock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
