# Generated by Django 5.0.6 on 2024-08-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_playeritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='Account/avatar_images/')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='player',
            name='avatar',
        ),
    ]
