# Generated by Django 5.0.6 on 2024-08-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_avatar_remove_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=255),
            preserve_default=False,
        ),
    ]
