# Generated by Django 5.0.6 on 2024-07-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=225)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchasable_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_logo', models.ImageField(blank=True, null=True, upload_to='Asset/currency_logo_images')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=225)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_img', models.ImageField(blank=True, null=True, upload_to='Asset/property_images')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=225)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchasable_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_logo', models.ImageField(blank=True, null=True, upload_to='Asset/stock_logo_images')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vehicle_img', models.ImageField(blank=True, null=True, upload_to='Asset/vehicle_images')),
                ('vehicle_type', models.CharField(choices=[('ماشین', 'ماشین'), ('هواپیما', 'هواپیما'), ('کشتی', 'کشتی')], max_length=255)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
