# Generated by Django 5.0.6 on 2024-07-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('base_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upgrade_cost_factor', models.DecimalField(decimal_places=2, default=1.15, max_digits=5)),
                ('category', models.CharField(choices=[('مغازه', 'مغازه'), ('شرکت', 'شرکت'), ('تولیدی', 'تولیدی'), ('واردات', 'واردات'), ('معدن', 'معدن'), ('کارخانه', 'کارخانه')], max_length=20)),
                ('ranking', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('business_image', models.ImageField(blank=True, null=True, upload_to='Account/Business_images/')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
