# Generated by Django 5.0.6 on 2024-07-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(default='This is a Business'),
            preserve_default=False,
        ),
    ]
